apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dropbox

images:
  - name: app-image
    newName: registry.gitlab.com/marekli/common/dropbox-docker
    newTag: v0.1.1

resources:
  - sealed-pull-secret.yaml
  - cm-dropbox-common.yaml
  - sts-dropbox-personal.yaml
  - sts-dropbox-ecogate.yaml

