apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pull-secret
  namespace: dropbox
spec:
  encryptedData:
    .dockerconfigjson: AgBLuItWHEO1cCcms5OrF43E4WsF4e7G3cs0FBGtFLhKlf5Hx5s42bd0rO9IwQHxeBDN8Rlgnu12Zeckq2bgIJnnx2eQocqjRJ+TW5ijCa+XsZlLGQo4WbZFEFo4VaJ0i6MNQ3VyeO68PF8YDeg4s3mBwhIV68Yyq9CXtnPjLo6TX2u5zFbl4IdmNYPhKt5NdNvUQWRTcFgx5W4NEnMqcsy1sIcbeVNX4EPBIVccL9GaupZgMkJFPLaG+4TsTLppKVfdsQchwwjLx+zhtU/qsfZtLcQtozIRcXCR5yCmPE2ovPr8lC4AKO+uCLMR/uw5n4Ib7x5BE9y4tjB6wB+kYVrp5qpwR3GwmSd23XvoAZ4BXPnQI+8AiJw8TCkiUwNhwZ8A+1un5zllf/qbgpuhkVpi8lsuvQoxy7VlkO5Bc7kYySqxKX7AWjLSlIADzyEhGyY3flWROObj9r8PkQrSeFuicdiV0SouOgAeT6CV6yaIK2vP2AXWueUQFPdUx9oHIzeg0v7OL5P3VnFC+hsQ237qz7gZaCy1VRo5ldH2oqp/qO/NryowZZ2Td48a+ycqt5UbPOD3YncbrTvvcDMgyFnirTlNzPq5KUMGcChnTPrR2K/j3g8DtCVSsD3t3UFCdJD0t3guh7Ub/sCXc6wSuFzOZsmdqkCjP6wdTNIn59MIynilZyCsEivL80U4+yR/leSvUmKlBx6jDW15wo2kG/lRbPvqri1sP7eiJH1IFq4WbkADwHnm3ovJ4WyJOBpKh2EuXnlIu7eh7sI9cyKW07C0Rg9f6bu3EO5aSsdOzhjk4qXc0ISHl0xv1RgZIMneJ0gOzbocyF9Nwgm52jaQq7vJrTAFq2Jk6wSwnBTQ5Pe4ECC/WsGPhc9lSVivKwPVWfN86lPof9ewU8VK7ocjtCrrtDQic9F88f/kjZbKZYkJFIXsOmemCBg=
  template:
    metadata:
      creationTimestamp: null
      name: pull-secret
      namespace: dropbox
    type: kubernetes.io/dockerconfigjson

