apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: dropbox-personal

spec:
  selector:
    matchLabels:
      app: dropbox
      account: personal

  replicas: 1
  serviceName: dropbox-personal
  podManagementPolicy: Parallel

  template:
    metadata:
      labels:
        app: dropbox
        account: personal

    spec:
      imagePullSecrets:
        - name: pull-secret

      containers:
        - name: dropbox
          image: dropbox-image

          envFrom:
            - configMapRef:
                name: dropbox-common

          volumeMounts:
            - name: dropbox-data
              mountPath: /opt/dropbox/Dropbox

            - name: dropbox-meta
              mountPath: /opt/dropbox/.dropbox

          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 256Mi
          #   # Limits are disabled due a CFS bug in the linux kernel causing
          #   # premature throttling.
          #   # https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718
          #   limits:
          #     cpu: 1000m
          #     memory: 1024Mi

      volumes:
        - name: dropbox-data
          hostPath:
            path: /vault/marekl/dropbox-personal
            type: DirectoryOrCreate

        - name: dropbox-meta
          hostPath:
            path: /vault/kubernetes/marekl-dropbox-meta-personal
            type: DirectoryOrCreate

  volumeClaimTemplates: []
